/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthDashboardImport } from './routes/_auth.dashboard'
import { Route as AuthDashboardStartImport } from './routes/_auth.dashboard.start'
import { Route as AuthDashboardMesformsImport } from './routes/_auth.dashboard.mesforms'
import { Route as AuthDashboardAnalyticsImport } from './routes/_auth.dashboard.analytics'

// Create Virtual Routes

const SignupLazyImport = createFileRoute('/signup')()
const LoginLazyImport = createFileRoute('/login')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SignupLazyRoute = SignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthDashboardRoute = AuthDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthDashboardStartRoute = AuthDashboardStartImport.update({
  path: '/start',
  getParentRoute: () => AuthDashboardRoute,
} as any)

const AuthDashboardMesformsRoute = AuthDashboardMesformsImport.update({
  path: '/mesforms',
  getParentRoute: () => AuthDashboardRoute,
} as any)

const AuthDashboardAnalyticsRoute = AuthDashboardAnalyticsImport.update({
  path: '/analytics',
  getParentRoute: () => AuthDashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard/analytics': {
      id: '/_auth/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthDashboardAnalyticsImport
      parentRoute: typeof AuthDashboardImport
    }
    '/_auth/dashboard/mesforms': {
      id: '/_auth/dashboard/mesforms'
      path: '/mesforms'
      fullPath: '/dashboard/mesforms'
      preLoaderRoute: typeof AuthDashboardMesformsImport
      parentRoute: typeof AuthDashboardImport
    }
    '/_auth/dashboard/start': {
      id: '/_auth/dashboard/start'
      path: '/start'
      fullPath: '/dashboard/start'
      preLoaderRoute: typeof AuthDashboardStartImport
      parentRoute: typeof AuthDashboardImport
    }
  }
}

// Create and export the route tree

interface AuthDashboardRouteChildren {
  AuthDashboardAnalyticsRoute: typeof AuthDashboardAnalyticsRoute
  AuthDashboardMesformsRoute: typeof AuthDashboardMesformsRoute
  AuthDashboardStartRoute: typeof AuthDashboardStartRoute
}

const AuthDashboardRouteChildren: AuthDashboardRouteChildren = {
  AuthDashboardAnalyticsRoute: AuthDashboardAnalyticsRoute,
  AuthDashboardMesformsRoute: AuthDashboardMesformsRoute,
  AuthDashboardStartRoute: AuthDashboardStartRoute,
}

const AuthDashboardRouteWithChildren = AuthDashboardRoute._addFileChildren(
  AuthDashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/dashboard': typeof AuthDashboardRouteWithChildren
  '/dashboard/analytics': typeof AuthDashboardAnalyticsRoute
  '/dashboard/mesforms': typeof AuthDashboardMesformsRoute
  '/dashboard/start': typeof AuthDashboardStartRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/dashboard': typeof AuthDashboardRouteWithChildren
  '/dashboard/analytics': typeof AuthDashboardAnalyticsRoute
  '/dashboard/mesforms': typeof AuthDashboardMesformsRoute
  '/dashboard/start': typeof AuthDashboardStartRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/_auth/dashboard': typeof AuthDashboardRouteWithChildren
  '/_auth/dashboard/analytics': typeof AuthDashboardAnalyticsRoute
  '/_auth/dashboard/mesforms': typeof AuthDashboardMesformsRoute
  '/_auth/dashboard/start': typeof AuthDashboardStartRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/mesforms'
    | '/dashboard/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/mesforms'
    | '/dashboard/start'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/_auth/dashboard'
    | '/_auth/dashboard/analytics'
    | '/_auth/dashboard/mesforms'
    | '/_auth/dashboard/start'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  SignupLazyRoute: typeof SignupLazyRoute
  AuthDashboardRoute: typeof AuthDashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
  AuthDashboardRoute: AuthDashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/login",
        "/signup",
        "/_auth/dashboard"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/signup": {
      "filePath": "signup.lazy.tsx"
    },
    "/_auth/dashboard": {
      "filePath": "_auth.dashboard.tsx",
      "children": [
        "/_auth/dashboard/analytics",
        "/_auth/dashboard/mesforms",
        "/_auth/dashboard/start"
      ]
    },
    "/_auth/dashboard/analytics": {
      "filePath": "_auth.dashboard.analytics.tsx",
      "parent": "/_auth/dashboard"
    },
    "/_auth/dashboard/mesforms": {
      "filePath": "_auth.dashboard.mesforms.tsx",
      "parent": "/_auth/dashboard"
    },
    "/_auth/dashboard/start": {
      "filePath": "_auth.dashboard.start.tsx",
      "parent": "/_auth/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
